name = "ohkami-worker-with-openapi"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-19"

# `worker-build` and `wasm-pack` is required
# (run `cargo install wasm-pack worker-build` to install)

[build]
command = "test $OHKAMI_WORKER_DEV && worker-build --dev || worker-build -- --no-default-features"

[vars]
VARIABLE_1 = "hoge"
VARIABLE_2 = "super fun"

[ai]
binding = "INTELIGENT"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[kv_namespaces]]
binding = "MY_KVSTORE"
id = "<BINDING_ID>"

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = '<YOUR_BUCKET_NAME>'

[[services]]
binding = "S"
service = "<WORKER_NAME>"

[[queues.producers]]
queue = "my-queue"
binding = "MY_QUEUE"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
