use ohkami_lib::{Slice, List};


/// This doesn't handle percent encoding by itself.
pub(crate) struct Path {
    raw:    Slice,
    #[allow(unused)]
    params: List<Slice, 2>,
}

#[cfg(any(feature="rt_tokio",feature="rt_async-std",feature="rt_worker"))]
impl Path {
    /// SAFETY: **NEVER** access to what is generated by this.
    #[inline] pub(crate) unsafe fn null() -> Self {
        Self {
            raw:    Slice::new_unchecked(std::ptr::null(), 0),
            params: List::new(),
        }
    }

    #[inline] pub(crate) unsafe fn from_request_bytes(bytes: &[u8]) -> Self {
        #[cfg(debug_assertions)]
        debug_assert! {
            bytes.starts_with(b"/")
        }
        
        /*
        Strip trailing '/' **even when `bytes` is just `b"/"`**
        (then the bytes become b"" (empty bytes)).
        
        This suits to ohkami's radix router's searching algorithm and,
        while `Path::as_internal_bytes` directly returns the result bytes,
        `Path::as_bytes`, intended to be used by `Request::{pub fn path(&self)}`,
        returns `b"/"` if that bytes is `b"/"`.
        */
        let mut len = bytes.len();
        if *bytes.get_unchecked(len-1) == b'/' {len -= 1};
        
        Self {
            raw:    Slice::new_unchecked(bytes.as_ptr(), len),
            params: List::new(),
        }
    }

    #[inline] pub(crate) fn push_param(&mut self, param: Slice) {
        self.params.push(param)
    }
    #[inline] pub(crate) unsafe fn assume_one_param<'p>(&self) -> &'p [u8] {
        self.params.get_unchecked(0).as_bytes()
    }
    #[inline] pub(crate) unsafe fn assume_two_params<'p>(&self) -> (&'p [u8], &'p [u8]) {
        (self.params.get_unchecked(0).as_bytes(), self.params.get_unchecked(1).as_bytes())
    }

    #[inline] pub(crate) unsafe fn as_internal_bytes<'req>(&self) -> &'req [u8] {
        self.raw.as_bytes()
    }

}

#[cfg(any(feature="rt_tokio",feature="rt_async-std"))]
#[cfg(test)] impl Path {
    pub(crate) fn from_literal(literal: &'static str) -> Self {
        Self { raw: unsafe {Slice::from_bytes(literal.as_bytes())}, params: List::new() }
    }
}

impl Path {
    #[inline] pub(crate) unsafe fn as_bytes<'req>(&self) -> &'req [u8] {
        match self.raw.as_bytes() {
            b""  => b"/",
            some => some,
        }
    }
}
