[package]
name               = "derive_from_request"
version            = "0.1.0"
edition            = "2024"

[dependencies]
ohkami             = { workspace = true }
tokio              = { workspace = true }