# This will be removed when ohkami has more than one maintainers

name: AutoApprove

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  approve:
    if: |
      github.event.pull_request.user.login == 'kanarus' &&
      !github.event.pull_request.draft
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
